Update Workflow to Incorporate Trusted Publisher Mechanism for Publishing to Test PyPI (#18)
# *Update Workflow to Incorporate Trusted Publisher Mechanism for
Publishing to Test PyPI*


## :gear: Release Notes 
This pull request updates the GitHub Actions workflow to incorporate the
trusted publisher mechanism for publishing our Python package to Test
PyPI.




## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code
of
Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md)
and [Contributing
Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of
Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md)
and [Contributing
Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

diff --git a/.github/workflows/publish-to-pypi.yml b/.github/workflows/publish-to-pypi.yml
--- a/.github/workflows/publish-to-pypi.yml
+++ b/.github/workflows/publish-to-pypi.yml
@@ -11,22 +11,78 @@ name: Publish Python Package
 on:
   push:
     tags:
-      - '*'
+      - "*"
+  workflow_dispatch:
+    inputs:
+      tag_name:
+        description: 'The tag name when the workflow is manually triggered.'
+        type: string
+        required: true
 
 jobs:
+  determine_environment:
+    runs-on: ubuntu-latest
+
+    outputs:
+      repo: ${{ steps.set-env.outputs.repo }}
+      environment: ${{ steps.set-env.outputs.environment }}
+      version: ${{ steps.set-env.outputs.version }}
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Determine target repository, environment, and version
+        id: set-env
+        run: |
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            if [[ "${{ github.event.inputs.tag_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+$ ]]; then
+              echo "repo=https://test.pypi.org/legacy/" >> $GITHUB_ENV
+              echo "environment=test" >> $GITHUB_ENV
+              echo "version=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
+              echo "::set-output name=repo=https://test.pypi.org/legacy/"
+              echo "::set-output name=environment=test"
+              echo "::set-output name=version=${{ github.event.inputs.tag_name }}"
+            else
+              echo "Workflow dispatch without a valid beta tag. Failing job."
+              exit 1
+            fi
+          elif echo ${GITHUB_REF##*/} | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
+            echo "repo=https://upload.pypi.org/legacy/" >> $GITHUB_ENV
+            echo "environment=release" >> $GITHUB_ENV
+            echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
+            echo "::set-output name=repo=https://upload.pypi.org/legacy/"
+            echo "::set-output name=environment=release"
+            echo "::set-output name=version=${GITHUB_REF##*/}"
+          elif echo ${GITHUB_REF##*/} | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+-(b[0-9]+|alpha\.[0-9]+)$'; then
+            echo "repo=https://test.pypi.org/legacy/" >> $GITHUB_ENV
+            echo "environment=test" >> $GITHUB_ENV
+            echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
+            echo "::set-output name=repo=https://test.pypi.org/legacy/"
+            echo "::set-output name=environment=test"
+            echo "::set-output name=version=${GITHUB_REF##*/}"
+          else
+            echo "Invalid ref for this workflow. Failing job."
+            exit 1
+          fi
+
   build_and_test:
+    needs: determine_environment
     uses: ./.github/workflows/build-and-test.yml
 
   build_and_publish:
-    needs: build_and_test
+    needs: [determine_environment, build_and_test]
     runs-on: ubuntu-latest
-    
+    environment: ${{ needs.determine_environment.outputs.environment }}
+    permissions:
+      id-token: write
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Set up Python
-        uses: actions/setup-python@v5  
+        uses: actions/setup-python@v5
 
       - name: Install dependencies
         run: |
@@ -39,10 +95,11 @@ jobs:
       - name: Update authors
         run: python scripts/update_authors.py
 
-      - name: Build and publish
-        env:
-          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
-          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-        run: |
-          hatch build
-          hatch publish
+      - name: Build package
+        run: hatch build
+
+      - name: Publish package distributions to PyPI/Test PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          repository-url: ${{ needs.determine_environment.outputs.repo }}
+          environment: ${{ needs.determine_environment.outputs.environment }}
